services:
  # Main API service
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DB_SEND_PASSWORD=${DB_SEND_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=*
    volumes:
      # Mount database file to persist data
      - ./chatterbox.db:/app/chatterbox.db
      - ./en_chatterbox_cards.json:/app/en_chatterbox_cards.json
      - ./fr_chatterbox_cards.json:/app/fr_chatterbox_cards.json
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
