services:
  # Main API service
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DB_SEND_PASSWORD=${DB_SEND_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=*
    volumes:
      # Mount database file to persist data
      - ./cue.db:/app/cue.db
      - ./en_cue_cards.json:/app/en_cue_cards.json
      - ./fr_cue_cards.json:/app/fr_cue_cards.json
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database backup job (runs on schedule)
  backup-job:
    build:
      context: .
      dockerfile: Dockerfile.backup
    environment:
      - API_URL=http://api:3000
      - BACKUP_EMAIL=${BACKUP_EMAIL:-admin@example.com}
      - DB_SEND_PASSWORD=${DB_SEND_PASSWORD}
    depends_on:
      - api
    restart: "no" # Don't restart on failure to prevent rate limit loops
    profiles:
      - backup # Only run when explicitly requested

networks:
  default:
    name: cue-network
